well_commerce_category:
    configuration:
        category:
            orm:
                manager: WellCommerce\Bundle\CategoryBundle\Manager\CategoryManager
                factory: WellCommerce\Bundle\CategoryBundle\Factory\CategoryFactory
                repository: WellCommerce\Bundle\CategoryBundle\Repository\CategoryRepository
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/Category.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            api:
                exposed: true
                dataset: category.dataset.admin
                manager: category.manager
            dynamic_routing:
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
                generator: WellCommerce\Bundle\CategoryBundle\Routing\CategoryRouteGenerator
                defaults:
                    _controller: category.controller.front:indexAction
                    limit: 12
                    page: 1
                    orderBy: name
                    orderDir: asc
                    priceFrom: 0
                    priceTo: 9999
                    view: grid
                    producers: ~
                    attributes: ~
                requirements:
                    limit: "\\d{1,10}"
                    page: "\\d{1,10}"
                    orderBy: "name|finalPrice"
                    orderDir: "asc|desc"
                    priceFrom: "\\d{1,10}"
                    priceTo: "\\d{1,10}"
                    view: "grid|list"
                    producers: "[\\d+_]+"
                    attributes: "[\\d+_]+"
                pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"
        category_route:
            orm:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/CategoryRoute.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
        category_translation:
            orm:
                manager: false
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation

