WellCommerce\Bundle\CategoryBundle\Entity\Category:
    fields:
        id:
            groups:
                - default
                - category
        hierarchy:
            groups:
                - default
                - category
        productsCount:
            groups:
                - default
                - category
        childrenCount:
            groups:
                - default
                - category
        enabled:
            groups:
                - default
                - category
    associations:
        parent:
            groups:
                - category
        translations:
            groups:
                - category
        shops:
            groups:
                - category
