# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_api:
    request_handler:
        category:
            manager: category.manager
    serialization:
        WellCommerce\Bundle\CategoryBundle\Entity\Category:
            mapping: "@WellCommerceCategoryBundle/Resources/config/serialization/Category.yml"
        WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute:
            mapping: "@WellCommerceCategoryBundle/Resources/config/serialization/CategoryRoute.yml"
        WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation:
            mapping: "@WellCommerceCategoryBundle/Resources/config/serialization/CategoryTranslation.yml"
